version: '3.8'

services:
  sdominanta_mcp:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sdominanta_mcp_app
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - ../:/app
    command: >
      sh -c "wait-for-it ollama_server:11434 -- uvicorn bridge.main:app --host 0.0.0.0 --port 8787"

  pa2ap_daemon:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: pa2ap_daemon_app
    restart: unless-stopped
    ports:
      - "9090:9090"
    command: ["node", "pa2ap/daemon/sdom-p2p.js"]

  ollama_server:
    image: ollama/ollama
    container_name: ollama_server
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
