version: '3.8'

networks:
  sdominanta_net:
    driver: bridge

services:
  app: # Объединенный сервис для FastAPI bridge и Node.js демона
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: sdominanta_app
    restart: unless-stopped
    ports:
      - "8787:8787" # Публикуем порт FastAPI bridge
      - "9090:9090" # Публикуем порт pa2ap daemon
    volumes:
      - ../wall/threads:/app/wall/threads # Сохраняем состояние стены
      - ../logs:/var/log/sdominanta # Сохраняем логи
    networks:
      - sdominanta_net
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - sdominanta_net
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_MAX_LOADED_MODELS=1 # Ограничиваем количество одновременно загруженных моделей
      - OLLAMA_NUM_PARALLEL=1     # Ограничиваем количество параллельных запросов

volumes:
  ollama_data:
