p2p_enabled: true
# URL WebSocket для подключения к P2P-демону (sdom-p2p.js)
p2p_ws_url: ws://127.0.0.1:9090

# Порт, на котором будет слушать FastAPI bridge
listen_port: 8787

# Настройки Git для работы со стеной (если archiver_enabled будет true)
# git:
#   auto_commit: true
#   author: "sdom-archiver <archiver@sdom.net>"

# Опции безопасности
security:
  require_signed_wall: true # Требовать подписи для публикаций на стену

# Настройки агентов (для будущих расширений)
# agents:
#   research_agent_id: "did:key:..."
