name = "sdominanta-wall-gw"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
GH_OWNER = "DumpKod"
GH_REPO  = "Sdominanta.net"
EVENT_TYPE = "wall-note"
ID_SALT = "set-strong-random-salt-here"


