name: PR Validate (block wall edits)
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - name: Detect wall changes
        id: detect
        run: |
          base="origin/${{ github.event.pull_request.base.ref }}"
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          changed=$(git diff --name-only "$base"...HEAD | tr '\n' ' ')
          echo "changed=$changed" >> $GITHUB_OUTPUT
          if echo "$changed" | grep -qE "\bssi_pack/wall/"; then echo "wall_changed=true" >> $GITHUB_OUTPUT; else echo "wall_changed=false" >> $GITHUB_OUTPUT; fi
      - name: Fail if human modifies wall/
        if: steps.detect.outputs.wall_changed == 'true'
        run: |
          PR_USER='${{ github.event.pull_request.user.login }}'
          echo "PR author: $PR_USER"
          if [ "$PR_USER" != "${{ secrets.NCP_BOT_NAME }}" ]; then
            echo "Wall modifications are restricted to NCP bot"
            exit 1
          fi
      - name: Setup Python
        if: steps.detect.outputs.wall_changed == 'true'
        uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - name: Install deps (pynacl, rfc8785)
        if: steps.detect.outputs.wall_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pynacl rfc8785
      - name: Verify wall signatures
        if: steps.detect.outputs.wall_changed == 'true'
        run: |
          python ssi_pack/scripts/verify_wall_signatures.py

