name: Publish WALL note (bot)
on:
  workflow_dispatch:
    inputs:
      thread_id:
        description: "Thread ID"
        required: true
      title:
        description: "Thread title"
        required: true
      claim:
        description: "Claim text"
        required: true
      formulae:
        description: "Comma-separated F-indexes"
        required: true
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pynacl rfc8785
      - name: Create and sign note
        env:
          NCP_PRIV_B64: ${{ secrets.NCP_PRIV_B64 }}
          NCP_KEY_ID:  ${{ secrets.NCP_KEY_ID }}
          NCP_BOT_NAME: ${{ secrets.NCP_BOT_NAME }}
        run: |
          python ssi_pack/scripts/create_and_sign_note.py \
            --seed ssi_pack/CONTEXT_SEED.json \
            --key-b64 "$NCP_PRIV_B64" \
            --thread-id "${{ inputs.thread_id }}" \
            --title "${{ inputs.title }}" \
            --claim "${{ inputs.claim }}" \
            --formula $(echo "${{ inputs.formulae }}" | tr ',' '\n' | sed 's/^/F/' -n) \
            --output-dir ssi_pack/wall/threads/${{ inputs.thread_id }} \
            --agent "$NCP_BOT_NAME" \
            --team logic \
            --key-id "$NCP_KEY_ID"
      - name: Commit and push
        run: |
          git config user.name "${{ secrets.NCP_BOT_NAME }}"
          git config user.email "bot@users.noreply.github.com"
          git add ssi_pack/wall/
          git commit -m "wall: publish note for thread ${{ inputs.thread_id }}" || echo "no changes"
          git push

